.TH "SMILE" "3" "July 2011" "smile"
.SH NAME
libsmile \- encode or decode files
.SH SYNOPSIS
.BR "include <api.h>"

.SH DESCRIPTON
.B Smile
is codename for an efficient JSON-compatible binary data format.

This library encodes and decodes Smile.

.\" .SH OPTIONS

.SH "SEE ALSO"
smile(1)

.SH AUTHOR
Pierre-Alexandre Meyer <pierre@mouraf.org>

http://github.com/pierre/libsmile

