.TH "SMILE" "1 "July 2011" "smile"
.SH NAME
smile \- encode or decode files
.SH SYNOPSIS
.BR "smile" "name"

.SH DESCRIPTON
.B Smile
is codename for an efficient JSON-compatible binary data format.

This utility decodes Smile binary files.

.\" .SH OPTIONS

.SH "SEE ALSO"
libsmile(3)

.SH AUTHOR
Pierre-Alexandre Meyer <pierre@mouraf.org>

http://github.com/pierre/libsmile

